### ISSUE TITLE
HiveTx not available in browser

### ISSUE THREAD

**Issue by Penderis** [mahdiyari/hive-tx-js#35]
I might be missing something obvious so I do apologise but I need to use Hive-tx in the browser context. 
This I assumed is simply using
```<script src="https://cdn.jsdelivr.net/npm/hive-tx/dist/hive-tx.min.js"></script>```

In my HTML doc and then either referencing it via window.hiveTx or hiveTx

However I cannot access the script at all, since Keychain does actually embed their script the console will pick up that Keychain is available but no reference to hiveTx is in the window context. 

Hivejs picks up in the window via cdn link and when logging hiveTx I can see this in the console 
![image](https://github.com/mahdiyari/hive-tx-js/assets/3405854/afed2b90-377b-46ac-b855-11670af81a17)

**Comment by mahdiyari** [comment]
This problem seems to have been introduced with v5.
You can add @4 to the url and use the v4 in the meantime while I push a fix for this problem.

https://cdn.jsdelivr.net/npm/hive-tx@4/dist/hive-tx.min.js
