### ISSUE TITLE
Catching Axios and internal library errors - mainly axios

### ISSUE THREAD

**Issue by Penderis** [mahdiyari/hive-tx-js#41]
Hi, I might be missing the boat completely and if I am just doing things wrong tips are welcome. 
I am not however able to catch the axios errors returned from the library via try catch blocks and the promise catch. 

Some are hard to test but this is the general error it will always return and then kill the node instance 
![image](https://github.com/mahdiyari/hive-tx-js/assets/3405854/f900dae3-32f3-42f8-9735-0c68120fed19)

The simplest way to reproduce is to use a wrong trx id on a account_history.get_transaction call 
```
try{
        console.log('test trx',req.params.trx)
        hive.call('account_history_api.get_transaction',[req.params.trx])
                            .then(result=> res.send(result))
                            .catch((err)=>{
                                console.log('promise catch',err)
                                throw new Error('f*#@ axios')
                            })       
    }catch(e){
        console.log('try catch',e)
        res.send(e)        
    }
````

but it would be the same for trying to use Privatekey.from on a wrong key. I am not sure how to catch these errors to avoid them crashing the instance.

**Comment by mahdiyari** [comment]
Are you sure your error is from this? An RPC error for wrong trx_id wouldn't evoke an error to begin with. It will be a normal result because the API will answer with a message.

I suspect the error is from something else that you are not catching.

**Comment by mahdiyari** [comment]
BTW I did write the above comment after testing your posted code.

**Comment by mahdiyari** [comment]
Also your format of the API call is wrong. Almost all the API methods other than `condenser_api` require an object input and not an array.

**Comment by mahdiyari** [comment]
Also, the "try catch" won't catch the error thrown in the promise catch in this code. You have to use await/async for your "try catch" to catch the errors from that promise. Try & catch on a promise won't catch the errors happening later without using await/async. That's why there is `.catch()` for non async codes.

**Comment by Penderis** [comment]
> Also your format of the API call is wrong. Almost all the API methods other than `condenser_api` require an object input and not an array. And API node will return an error telling you this. You can replace account_history_api with condenser_api for quick fix.

It works with that although I did notice I use an object in other ones, not sure how settled on that one but yeah it works. I did run test now using object id:trx and still returns result if correct TRX id. I will test with condenser also. I merely used this one as the simplest way to reproduce the issue.

**Comment by Penderis** [comment]
> Also, the "try catch" won't catch the error thrown in the promise catch in this code. You have to use await/async for your "try catch" to catch the errors from that promise. Try & catch on a promise won't catch the errors happening later without using await/async. That's why there is `.catch()` for non async codes.

Thank you, I kinda did not click that but the catch from the .then format should though catch the error? I did change it from await just to have both catches there without thinking that it would be pointless. I will setup an await one only for testing.

**Comment by Penderis** [comment]
> Are you sure your error is from this? An RPC error for wrong trx_id wouldn't evoke an error to begin with. It will be a normal result because the API will answer with a message.
> 
> I suspect the error is from something else that you are not catching.

This could be then from express , although I only get it with hive-tx calls , for thoroughness I will test using fetch directly which I know returns me the rpc error if there is one also but exact call to see which fails. Thank you, I will look into it then sorry for the hassle.
